# Generated by Django 3.2.8 on 2021-10-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('company_username', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'user_carts',
            },
        ),
    ]
