# Generated by Django 3.2.8 on 2021-10-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField()),
                ('company_username', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=30)),
                ('product_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_source', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'company_inventory',
            },
        ),
    ]
