# Generated by Django 3.2.8 on 2021-10-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyInventory', '0003_auto_20211022_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinventory',
            name='image_source',
            field=models.ImageField(blank=True, default='company_items/default_item.png', max_length=50, null=True, upload_to='company_items'),
        ),
    ]
