# Generated by Django 3.2.8 on 2021-10-08 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companySignUp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=512)),
                ('avg_review', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('open_time', models.CharField(max_length=12)),
                ('close_time', models.CharField(max_length=12)),
                ('contact_phone', models.IntegerField()),
                ('contact_email', models.CharField(max_length=80)),
                ('website', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'company_profile',
            },
        ),
    ]
